swiftmailer:
    transport:        gmail
    username:         tt9930828@gmail.com
    password:         Test12345678
    host:             localhost
    port:             465
    encryption:       ssl
    auth-mode:        login
    spool: { type: 'memory' }
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false